name: Publish Address Book Package

on:
  push:
    branches:
      - master
    paths:
      - packages/address-book/**
      - '!packages/address-book/package.json'
      - '!packages/address-book/CHANGELOG.md'
      - '!packages/address-book/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    defaults:
      run:
        working-directory: packages/address-book
    steps:
      # get repo code
      - uses: actions/checkout@v4
      # install node
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '../../.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          scope: 'beefyfinance'
      # install packages
      - run: npm ci
      # run checksum test
      - run: npm run checksum
      # transpile from Typescript to Javascript
      - run: npm run compile
      # bump package version and commit. Note that this won't create an infinite github action push loop, as we have added package.json to paths-ignore.
      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@v9.1.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: 'packages/address-book'
      # publish package
      - run: npm publish
